// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA2CD7CT87x1bKgr-3TRmPtq_KOLB53mA',
    appId: '1:884979148308:web:fae76173c469b1b0986901',
    messagingSenderId: '884979148308',
    projectId: 'login-admin-9eaaf',
    authDomain: 'login-admin-9eaaf.firebaseapp.com',
    storageBucket: 'login-admin-9eaaf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ9AF_vUdFk4v-H4zrZDlmM22PhaFWeLA',
    appId: '1:884979148308:android:cd9145becc29fa33986901',
    messagingSenderId: '884979148308',
    projectId: 'login-admin-9eaaf',
    storageBucket: 'login-admin-9eaaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfz9y9CJBjUKthStY4-4wyaSbvy6vFvQo',
    appId: '1:884979148308:ios:4254c188717fa76a986901',
    messagingSenderId: '884979148308',
    projectId: 'login-admin-9eaaf',
    storageBucket: 'login-admin-9eaaf.firebasestorage.app',
    iosBundleId: 'com.example.gdgSoogsilSolutionChallenge1teamFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfz9y9CJBjUKthStY4-4wyaSbvy6vFvQo',
    appId: '1:884979148308:ios:4254c188717fa76a986901',
    messagingSenderId: '884979148308',
    projectId: 'login-admin-9eaaf',
    storageBucket: 'login-admin-9eaaf.firebasestorage.app',
    iosBundleId: 'com.example.gdgSoogsilSolutionChallenge1teamFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA2CD7CT87x1bKgr-3TRmPtq_KOLB53mA',
    appId: '1:884979148308:web:6a509f94405fe188986901',
    messagingSenderId: '884979148308',
    projectId: 'login-admin-9eaaf',
    authDomain: 'login-admin-9eaaf.firebaseapp.com',
    storageBucket: 'login-admin-9eaaf.firebasestorage.app',
  );

}